### PR TITLE
Update libraries

### PR DESCRIPTION
**Pull request by p2004a**
- zlib 1.2.13 -> 1.3
- zlib-ng 1.9.9-b1 -> 2.1.5
- jpeg 9d -> 9e
- tiff 4.1 -> 4.6
- libunwind 1.4.0 -> 1.6.2
- openssl 1.1.1s -> 3.2.0
- nghttp2 1.51 -> 1.58
- curl 7.86 -> 8.5
- libogg 1.3.4 -> 1.3.5
- lzma 5.2.5 -> 5.4.5
- minizip 3.0.7 -> 3.0.10

### CODE REVIEW

**Comment by Beherith** [comment]
Does it compile? :D

**Comment by p2004a** [comment]
Did a full local build of engine with new libs and I've not noticed any issues

**Comment by p2004a** [comment]
(I've skipped updating libpng as there was some compilation error and decided not to invest time into figuring out what's wrong)

**Comment by Beherith** [comment]
Is libunwind the one responsible for generating stack traces?

**Comment by p2004a** [comment]
> Is libunwind the one responsible for generating stack traces?
Yes, it's used in that process

**Pull request closed without merging**
